name: C++ CI and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # Required for creating releases and uploading assets

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libx11-dev \
          libxext-dev \
          libasound2-dev

    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release --verbose

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: build/avbd_demo3d

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2

    - name: Clone and Bootstrap vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
      shell: powershell

    - name: Set VCPKG_ROOT and add to PATH
      run: |
        echo "VCPKG_ROOT=${{ github.workspace }}\vcpkg" >> $env:GITHUB_ENV
        echo "${{ github.workspace }}\vcpkg" >> $env:GITHUB_PATH
      shell: powershell

    - name: Install dependencies
      run: vcpkg install opengl glad
      shell: cmd

    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}\scripts\buildsystems\vcpkg.cmake
        cmake --build . --config Release --verbose
      shell: cmd

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build/Release/avbd_demo3d.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: brew install sdl2 pkg-config

    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_FLAGS="-F/Library/Frameworks -framework OpenGL"
        cmake --build . --config Release --verbose

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: build/avbd_demo3d

  build-web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: '3.1.55'
        actions-cache-folder: 'emsdk-cache'

    - name: Install Ninja
      run: sudo apt-get update && sudo apt-get install -y ninja-build

    - name: Configure and Build
      run: |
        source "${{ env.EMSDK }}/emsdk_env.sh"
        mkdir build-web
        cd build-web
        emcmake cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-s USE_SDL=2 -s USE_WEBGL2=1" ..
        ninja --verbose

    - name: List Build Outputs
      run: ls -l build-web/
      working-directory: ${{ github.workspace }}

    - name: Upload Web Artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: |
          build-web/*.html
          build-web/*.js
          build-web/*.wasm

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos, build-web]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Linux Artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-build
        path: artifacts/linux

    - name: Download Windows Artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-build
        path: artifacts/windows

    - name: Download macOS Artifact
      uses: actions/download-artifact@v4
      with:
        name: macos-build
        path: artifacts/macos

    - name: Download Web Artifact
      uses: actions/download-artifact@v4
      with:
        name: web-build
        path: artifacts/web

    - name: Check Web Artifacts
      run: |
        echo "Checking for Web artifacts in artifacts/web/"
        ls -l artifacts/web/ || echo "No Web artifacts found"
        [ -f artifacts/web/avbd_demo3d.html ] && echo "HTML_FOUND=true" >> $GITHUB_ENV || echo "HTML_FOUND=false" >> $GITHUB_ENV
        [ -f artifacts/web/avbd_demo3d.js ] && echo "JS_FOUND=true" >> $GITHUB_ENV || echo "JS_FOUND=false" >> $GITHUB_ENV
        [ -f artifacts/web/avbd_demo3d.wasm ] && echo "WASM_FOUND=true" >> $GITHUB_ENV || echo "WASM_FOUND=false" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Linux Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/linux/avbd_demo3d
        asset_name: avbd_demo3d-linux
        asset_content_type: application/octet-stream

    - name: Upload Windows Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/windows/avbd_demo3d.exe
        asset_name: avbd_demo3d-windows.exe
        asset_content_type: application/octet-stream

    - name: Upload macOS Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/macos/avbd_demo3d
        asset_name: avbd_demo3d-macos
        asset_content_type: application/octet-stream

    - name: Upload Web HTML Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/web/avbd_demo3d.html
        asset_name: avbd_demo3d.html
        asset_content_type: text/html
      if: env.HTML_FOUND == 'true'

    - name: Upload Web JS Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/web/avbd_demo3d.js
        asset_name: avbd_demo3d.js
        asset_content_type: application/javascript
      if: env.JS_FOUND == 'true'

    - name: Upload Web WASM Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: artifacts/web/avbd_demo3d.wasm
        asset_name: avbd_demo3d.wasm
        asset_content_type: application/wasm
      if: env.WASM_FOUND == 'true'

  prerelease:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos, build-web]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Delete existing prerelease if exists
      uses: actions/github-script@v7
      with:
        script: |
          const releases = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          const prerelease = releases.data.find(r => r.tag_name === 'prerelease');
          if (prerelease) {
            await github.rest.repos.deleteRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: prerelease.id
            });
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/prerelease'
            });
          }

    - name: Create prerelease tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag prerelease ${{ github.sha }}
        git push origin prerelease --force

    - name: Download Linux Artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-build
        path: artifacts/linux

    - name: Download Windows Artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-build
        path: artifacts/windows

    - name: Download macOS Artifact
      uses: actions/download-artifact@v4
      with:
        name: macos-build
        path: artifacts/macos

    - name: Download Web Artifact
      uses: actions/download-artifact@v4
      with:
        name: web-build
        path: artifacts/web

    - name: Check Web Artifacts
      run: |
        echo "Checking for Web artifacts in artifacts/web/"
        ls -l artifacts/web/ || echo "No Web artifacts found"
        [ -f artifacts/web/avbd_demo3d.html ] && echo "HTML_FOUND=true" >> $GITHUB_ENV || echo "HTML_FOUND=false" >> $GITHUB_ENV
        [ -f artifacts/web/avbd_demo3d.js ] && echo "JS_FOUND=true" >> $GITHUB_ENV || echo "JS_FOUND=false" >> $GITHUB_ENV
        [ -f artifacts/web/avbd_demo3d.wasm ] && echo "WASM_FOUND=true" >> $GITHUB_ENV || echo "WASM_FOUND=false" >> $GITHUB_ENV

    - name: Create Prerelease
      id: create_prerelease
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: prerelease
        release_name: Prerelease Build
        draft: false
        prerelease: true

    - name: Upload Linux Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_prerelease.outputs.upload_url }}
        asset_path: artifacts/linux/avbd_demo3d
        asset_name: avbd_demo3d-linux
        asset_content_type: application/octet-stream

    - name: Upload Windows Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_prerelease.outputs.upload_url }}
        asset_path: artifacts/windows/avbd_demo3d.exe
        asset_name: avbd_demo3d-windows.exe
        asset_content_type: application/octet-stream

    - name: Upload macOS Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_prerelease.outputs.upload_url }}
        asset_path: artifacts/macos/avbd_demo3d
        asset_name: avbd_demo3d-macos
        asset_content_type: application/octet-stream

    - name: Upload Web HTML Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_prerelease.outputs.upload_url }}
        asset_path: artifacts/web/avbd_demo3d.html
        asset_name: avbd_demo3d.html
        asset_content_type: text/html
      if: env.HTML_FOUND == 'true'

    - name: Upload Web JS Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_prerelease.outputs.upload_url }}
        asset_path: artifacts/web/avbd_demo3d.js
        asset_name: avbd_demo3d.js
        asset_content_type: application/javascript
      if: env.JS_FOUND == 'true'

    - name: Upload Web WASM Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_prerelease.outputs.upload_url }}
        asset_path: artifacts/web/avbd_demo3d.wasm
        asset_name: avbd_demo3d.wasm
        asset_content_type: application/wasm
      if: env.WASM_FOUND == 'true'
