name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2

    - name: Create build directory
      run: |
        mkdir build
        cd build

    - name: Configure CMake
      run: cmake ..
      working-directory: build

    - name: Build
      run: cmake --build . --config Release
      working-directory: build
